import { describe,expect,it } from "vitest";
import { attendanceRepository } from "../src/repositories/attendanceRepository";
import { timetableRepository } from "../src/repositories/timetableRepository";
import { alertRepository } from "../src/repositories/alertRepository";
import { attendanceService, calculateProjection, calculateStatistics } from "../src/services/attendanceService";
import { getCurrentTimetableSubjects, timetableService } from "../src/services/timetableService";
import { onboard } from "./helpers";
import { applicationService } from "../src/services/applicationService";

describe("attendance and timetable",()=>{
  it("calculates every status and changed-subject attendance correctly",()=>{const rows:any[]=[{id:"1",date:"2026-08-01",subjectId:"s1",status:"present"},{id:"2",date:"2026-08-02",subjectId:"s1",status:"absent"},{id:"3",date:"2026-08-03",subjectId:"s1",status:"cancelled"},{id:"4",date:"2026-08-04",subjectId:"s1",status:"unmarked"},{id:"5",date:"2026-08-05",subjectId:"s1",status:"changed",changedToSubjectId:"s2"}];const stats=calculateStatistics(rows,["s1","s2"]);expect(stats).toMatchObject({present:2,counted:3});expect(stats.bySubject.find(x=>x.subjectId==="s1")).toMatchObject({present:1,total:2,pct:50});expect(stats.bySubject.find(x=>x.subjectId==="s2")).toMatchObject({present:1,total:1,pct:100});});
  it("calculates recovery, safe misses, and next-class projection",()=>{expect(calculateProjection(7,10,75)).toMatchObject({classesNeeded:2,canMiss:0});expect(calculateProjection(9,10,75)).toMatchObject({classesNeeded:0,canMiss:2});expect(calculateProjection(7,10,75,2).projected).toBeCloseTo(75);});
  it("versions timetable changes atomically and preserves or clears history by mode",async()=>{const subject=await onboard();const slots=[{id:"ui-slot",dayOfWeek:1,period:1,subjectId:subject.id,startTime:"09:00",endTime:"10:00"}];await timetableService.replace({subjects:[subject],slots,keepMode:"all",activeFrom:"2026-08-01"});await attendanceService.markAttendance({date:"2026-08-04",subjectId:subject.id,status:"present"});await timetableService.replace({subjects:[subject],slots,keepMode:"all",activeFrom:"2026-09-01"});expect((await attendanceRepository.getAll()).length).toBe(1);expect((await timetableRepository.getActive("2026-08-15")).activeTo).toBe("2026-08-31");await timetableService.replace({subjects:[subject],slots,keepMode:"fresh",activeFrom:"2026-10-01"});expect(await attendanceRepository.getAll()).toHaveLength(0);});
  it("lists only subjects referenced by the current timetable",()=>{const oldSubject={id:"old",name:"Old Subject",shortName:"OLD",color:"#111111"};const currentSubject={id:"new",name:"New Subject",shortName:"NEW",color:"#222222"};const slots=[{id:"slot",dayOfWeek:1,period:1,subjectId:"new",startTime:"09:00",endTime:"10:00"}];expect(getCurrentTimetableSubjects([oldSubject,currentSubject],slots)).toEqual([currentSubject]);});
  it("removes subjects from the app state when a new timetable replaces them",async()=>{const oldSubject=await onboard();await timetableService.replace({subjects:[oldSubject],slots:[{id:"old-slot",dayOfWeek:1,period:1,subjectId:oldSubject.id,startTime:"09:00",endTime:"10:00"}],keepMode:"all",activeFrom:"2026-08-01"});const newSubject={id:"new-ui",name:"Operating Systems",shortName:"OS",color:"#222222"};await timetableService.replace({subjects:[newSubject],slots:[{id:"new-slot",dayOfWeek:2,period:1,subjectId:newSubject.id,startTime:"10:00",endTime:"11:00"}],keepMode:"all",activeFrom:"2026-09-01"});const state=await applicationService.load();expect(state.subjects.map(subject=>subject.name)).toEqual(["Operating Systems"]);expect(state.subjects.map(subject=>subject.name)).not.toContain("Database Systems");});
  it("deduplicates threshold alerts for an unchanged attendance state",async()=>{const subject=await onboard();await attendanceRepository.upsert({date:"2026-08-01",subjectId:subject.id,status:"absent"});const state={attendanceRecords:await attendanceRepository.getAll(),subjects:[subject],attendanceThreshold:75};await attendanceService.evaluateThreshold(state);await attendanceService.evaluateThreshold(state);expect(await alertRepository.getAll()).toHaveLength(1);});
});
