import { describe,expect,it } from "vitest";
import JSZip from "jszip";
import { backupService } from "../src/services/backupService";
import { resetService } from "../src/services/resetService";
import { applicationService } from "../src/services/applicationService";
import { assignmentService } from "../src/services/assignmentService";
import { localFileService } from "../src/services/fileService";
import { onboard } from "./helpers";
import { getDatabase } from "../src/database/database";

describe("backup, restore, persistence, and reset",()=>{
  it("restores the SQLite database and local files after reset",async()=>{const subject=await onboard();await assignmentService.save({id:"a1",name:"Persistent",subjectId:subject.id,deadline:"2026-09-01",status:"pending",notes:"",files:[]});await localFileService.importFile("app-data/assignments/a1/note.txt",new Blob(["hello"],{type:"text/plain"}));const blob=await backupService.exportBackup();await resetService.resetApplication();expect((await applicationService.load()).onboardingComplete).toBe(false);await backupService.importBackup(blob);const state=await applicationService.load();expect(state.assignments.map(x=>x.name)).toContain("Persistent");expect((await localFileService.exportAll()).map(x=>x.path)).toContain("app-data/assignments/a1/note.txt");});
  it("reset removes every user-owned database row and returns to onboarding",async()=>{await onboard();await resetService.resetApplication();const state=await applicationService.load();expect(state.onboardingComplete).toBe(false);expect(state.profile.name).toBe("");for(const key of ["subjects","timetable","attendanceRecords","assignments","competitions","reminders","transactions","categories","alerts"] as const)expect(state[key]).toHaveLength(0);const db=await getDatabase();for(const table of ["users","user_settings","subjects","timetable_versions","timetable_slots","attendance_records","assignments","assignment_files","competitions","competition_rounds","competition_files","reminders","categories","transactions","alerts","notification_schedules"]){expect(db.first<{count:number}>(`SELECT COUNT(*) count FROM ${table}`)?.count,table).toBe(0);}});
  it("rejects traversal paths before writing restored files",async()=>{await onboard();const backup=await backupService.exportBackup();const zip=await JSZip.loadAsync(await backup.arrayBuffer());const manifest=JSON.parse(await zip.file("manifest.json")!.async("string"));manifest.files=[{path:"app-data/assignments/../../database.sqlite",size:1,type:"text/plain"}];zip.file("manifest.json",JSON.stringify(manifest));const malicious=await zip.generateAsync({type:"blob"});await expect(backupService.importBackup(malicious)).rejects.toThrow(/unsafe|duplicate/i);await expect(localFileService.importFile("app-data/assignments/../../database.sqlite",new Blob(["x"]))).rejects.toThrow(/invalid local file path/i);});
  it("rejects manifest file sizes above the per-file limit",async()=>{await onboard();const backup=await backupService.exportBackup();const zip=await JSZip.loadAsync(await backup.arrayBuffer());const manifest=JSON.parse(await zip.file("manifest.json")!.async("string"));manifest.files=[{path:"app-data/assignments/a1/large.txt",size:26*1024*1024,type:"text/plain"}];zip.file("manifest.json",JSON.stringify(manifest));const malicious=await zip.generateAsync({type:"blob"});await expect(backupService.importBackup(malicious)).rejects.toThrow(/invalid size/i);});
});
