import { describe,expect,it } from "vitest";
import { assignmentService, getAssignmentStatus } from "../src/services/assignmentService";
import { assignmentRepository } from "../src/repositories/assignmentRepository";
import { competitionRepository } from "../src/repositories/competitionRepository";
import { reminderRepository } from "../src/repositories/reminderRepository";
import { nextReminderOccurrence } from "../src/services/reminderRecurrence";
import { transactionRepository } from "../src/repositories/transactionRepository";
import { categoryRepository } from "../src/repositories/categoryRepository";
import { alertRepository } from "../src/repositories/alertRepository";
import { onboard } from "./helpers";
import { reminderService } from "../src/services/reminderService";
import { competitionService } from "../src/services/competitionService";
import { timetableService } from "../src/services/timetableService";
import { attendanceRepository } from "../src/repositories/attendanceRepository";

describe("local domain repositories",()=>{
  it("derives assignment status and supports renaming and removing file metadata",async()=>{const subject=await onboard();const assignment=await assignmentService.save({id:"a1",name:"Lab",subjectId:subject.id,deadline:"2026-08-18",status:"pending",notes:"",files:[]});expect(getAssignmentStatus(assignment,"2026-08-19")).toBe("overdue");const file=await assignmentRepository.addFile("a1",{name:"lab.pdf",fileType:"application/pdf",localPath:"app-data/assignments/a1/file.pdf",size:12});await assignmentRepository.renameFile(file.id,"Answer sheet.pdf");expect((await assignmentRepository.getById("a1"))?.files[0].name).toBe("Answer sheet.pdf");await assignmentRepository.deleteFile(file.id);expect((await assignmentRepository.getById("a1"))?.files).toHaveLength(0);await assignmentRepository.delete("a1");expect(await assignmentRepository.getById("a1")).toBeUndefined();});
  it("keeps competition documents separate from the certificate and supports renaming",async()=>{await onboard();await competitionRepository.save({id:"c1",name:"Hack",teamName:"A",type:"hackathon",status:"upcoming",celebrationShown:false,rounds:[{id:"r1",label:"Final",date:"2026-09-01",status:"upcoming"}]});await competitionRepository.addFile("c1",{id:"d1",name:"rules.pdf",fileType:"application/pdf",localPath:"app-data/competitions/c1/rules.pdf"},"document");await competitionRepository.setCertificate("c1",{id:"f1",name:"cert.pdf",fileType:"application/pdf",localPath:"app-data/competitions/c1/cert.pdf"});await competitionRepository.renameFile("d1","Competition rules.pdf");expect(await competitionRepository.getById("c1")).toMatchObject({rounds:[{id:"r1"}],documents:[{id:"d1",name:"Competition rules.pdf"}],certificate:{id:"f1"}});});
  it("advances once, daily, weekly, monthly, and yearly reminders locally",async()=>{await onboard();const now=new Date(2026,7,19,9);expect(nextReminderOccurrence("2026-08-20","08:00","once",now)?.getDate()).toBe(20);expect(nextReminderOccurrence("2026-08-19","08:00","daily",now)?.getDate()).toBe(20);expect(nextReminderOccurrence("2026-08-12","08:00","weekly",now)?.getDate()).toBe(26);expect(nextReminderOccurrence("2026-07-31","08:00","monthly",now)?.getMonth()).toBe(7);expect(nextReminderOccurrence("2025-08-19","08:00","yearly",now)?.getFullYear()).toBe(2027);await reminderRepository.save({id:"r",message:"Study",date:"2026-08-20",time:"18:00",frequency:"once"});expect(await reminderRepository.getAll()).toHaveLength(1);});
  it("stores exact positive money and aggregates by month/category",async()=>{await onboard();const category=(await categoryRepository.getAll()).find(x=>x.type==="expense")!;const income=(await categoryRepository.getAll()).find(x=>x.type==="income")!;await transactionRepository.save({id:"i",type:"income",categoryId:income.id,amount:1000.25,account:"Cash",date:"2026-08-01",comment:""});await transactionRepository.save({id:"e",type:"expense",categoryId:category.id,amount:250.1,account:"UPI",date:"2026-08-02",comment:"Lunch"});const summary=await transactionRepository.getMonthlySummary("2026-08");expect(summary).toMatchObject({income:1000.25,expense:250.1,balance:750.15});await expect(transactionRepository.save({id:"bad",type:"expense",categoryId:category.id,amount:0,account:"Cash",date:"2026-08-03",comment:""})).rejects.toThrow(/greater than zero/);});
  it("marks alerts read and enforces dedupe keys",async()=>{await onboard();const alert={title:"Test",message:"Message",timestamp:new Date().toISOString(),read:false,alertType:"system" as const,dedupeKey:"same"};await alertRepository.create(alert);await alertRepository.create(alert);expect(await alertRepository.getAll()).toHaveLength(1);await alertRepository.markAllRead();expect((await alertRepository.getAll())[0]?.read).toBe(true);});
  it("rejects impossible reminder dates and past one-time reminders",async()=>{await onboard();await expect(reminderService.save({id:"invalid",message:"Test",date:"2026-02-31",time:"10:00",frequency:"once"})).rejects.toThrow(/valid reminder date/);await expect(reminderService.save({id:"past",message:"Test",date:"2020-01-01",time:"10:00",frequency:"once"})).rejects.toThrow(/future/);});
  it("requires a custom label for other competitions",async()=>{await onboard();await expect(competitionService.save({id:"c",name:"Event",teamName:"Team",type:"other",status:"upcoming",celebrationShown:false,rounds:[]})).rejects.toThrow(/Custom competition type/);});
  it("rejects duplicate timetable periods and invalid class times",async()=>{const subject=await onboard();const base={id:"1",dayOfWeek:1,period:1,subjectId:subject.id,startTime:"10:00",endTime:"09:00"};await expect(timetableService.replace({subjects:[subject],slots:[base],keepMode:"all"})).rejects.toThrow(/end after/);await expect(timetableService.replace({subjects:[subject],slots:[{...base,endTime:"11:00"},{...base,id:"2",endTime:"12:00"}],keepMode:"all"})).rejects.toThrow(/duplicate periods/);});
  it("can clear the data owned by every main page",async()=>{const subject=await onboard();const category=(await categoryRepository.getAll())[0];await attendanceRepository.upsert({date:"2026-09-01",subjectId:subject.id,status:"present"});await assignmentService.save({id:"a",name:"Task",subjectId:subject.id,deadline:"2026-10-01",status:"pending",notes:"",files:[]});await competitionService.save({id:"c",name:"Contest",teamName:"Team",type:"ctf",status:"upcoming",celebrationShown:false,rounds:[]});await reminderRepository.save({id:"r",message:"Review",date:"2027-01-01",time:"10:00",frequency:"once"});await transactionRepository.save({id:"t",type:"expense",categoryId:category.id,amount:25,account:"Cash",date:"2026-09-01",comment:""});await attendanceRepository.deleteAll();await assignmentService.deleteAll();await competitionService.deleteAll();await reminderService.deleteAll();await transactionRepository.deleteAll();expect(await attendanceRepository.getAll()).toHaveLength(0);expect(await assignmentRepository.getAll()).toHaveLength(0);expect(await competitionRepository.getAll()).toHaveLength(0);expect(await reminderRepository.getAll()).toHaveLength(0);expect(await transactionRepository.getAll()).toHaveLength(0);});
});
