// Central re-export — import everything from '@/api'
export * from './client'
export * from './auth'
export * from './profile'
export * from './attendance'
export * from './assignments'
export * from './competitions'
export * from './reminders'
export * from './expense'
export * from './alerts'
