import { getDatabase } from "../database/database";
import { createId, nowIso } from "../database/ids";
import type { Competition, CompetitionRound, FileAttachment } from "../types";
import { requireLocalUserId } from "./helpers";

type Row={id:string;name:string;team_name:string;type:Competition["type"];custom_type:string|null;status:Competition["status"];celebration_shown:number};
type RoundRow={id:string;label:string;date:string;status:CompetitionRound["status"]};
type FileRow={id:string;original_name:string;local_path:string;mime_type:string;file_size:number;file_role:'document'|'certificate'};
const fileMap=(file:FileRow):FileAttachment=>({id:file.id,name:file.original_name,fileType:file.mime_type,localPath:file.local_path,size:file.file_size});

async function mapCompetition(row:Row):Promise<Competition>{const db=await getDatabase();const rounds=db.all<RoundRow>("SELECT id,label,date,status FROM competition_rounds WHERE competition_id=? ORDER BY date",[row.id]);const files=db.all<FileRow>("SELECT * FROM competition_files WHERE competition_id=? ORDER BY created_at",[row.id]);const certificate=files.filter(file=>file.file_role==='certificate').at(-1);return{id:row.id,name:row.name,teamName:row.team_name,type:row.type,customType:row.custom_type??undefined,status:row.status,celebrationShown:row.celebration_shown===1,rounds,documents:files.filter(file=>file.file_role==='document').map(fileMap),certificate:certificate?fileMap(certificate):undefined};}

export const competitionRepository={
  async getAll():Promise<Competition[]>{const db=await getDatabase();return Promise.all(db.all<Row>("SELECT * FROM competitions ORDER BY created_at DESC").map(mapCompetition));},
  async getById(id:string):Promise<Competition|undefined>{const db=await getDatabase();const row=db.first<Row>("SELECT * FROM competitions WHERE id=?",[id]);return row?mapCompetition(row):undefined;},
  async save(value:Competition):Promise<Competition>{const db=await getDatabase();const userId=await requireLocalUserId();const timestamp=nowIso();const next={...value,id:value.id||createId()};await db.transaction(async()=>{await db.run(`INSERT INTO competitions VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,team_name=excluded.team_name,type=excluded.type,custom_type=excluded.custom_type,status=excluded.status,celebration_shown=excluded.celebration_shown,updated_at=excluded.updated_at`,[next.id,userId,next.name,next.teamName,next.type,next.customType??null,next.status,next.celebrationShown?1:0,timestamp,timestamp]);for(const round of next.rounds)await this.saveRound(next.id,round);});return next;},
  async update(id:string,changes:Partial<Competition>):Promise<Competition>{const current=await this.getById(id);if(!current)throw new Error("Competition not found");return this.save({...current,...changes,id});},
  async saveRound(competitionId:string,round:CompetitionRound):Promise<CompetitionRound>{const db=await getDatabase();const timestamp=nowIso();await db.run(`INSERT INTO competition_rounds VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET label=excluded.label,date=excluded.date,status=excluded.status,updated_at=excluded.updated_at`,[round.id||createId(),competitionId,round.label,round.date,round.status,timestamp,timestamp]);return round;},
  async delete(id:string):Promise<FileAttachment[]>{const current=await this.getById(id);const db=await getDatabase();await db.run("DELETE FROM competitions WHERE id=?",[id]);return [...(current?.documents??[]),...(current?.certificate?[current.certificate]:[])];},
  async deleteAll():Promise<FileAttachment[]>{const current=await this.getAll();const db=await getDatabase();await db.run("DELETE FROM competitions");return current.flatMap(item=>[...(item.documents??[]),...(item.certificate?[item.certificate]:[])]);},
  async addFile(competitionId:string,file:FileAttachment,role:'document'|'certificate'='document'):Promise<FileAttachment>{const db=await getDatabase();await db.run("INSERT INTO competition_files (id,competition_id,original_name,local_path,mime_type,file_size,created_at,file_role) VALUES (?,?,?,?,?,?,?,?)",[file.id,competitionId,file.name,file.localPath??"",file.fileType,file.size??0,nowIso(),role]);return file;},
  async deleteFile(id:string):Promise<FileAttachment|undefined>{const db=await getDatabase();const row=db.first<FileRow>("SELECT * FROM competition_files WHERE id=?",[id]);await db.run("DELETE FROM competition_files WHERE id=?",[id]);return row?fileMap(row):undefined;},
  async renameFile(id:string,name:string):Promise<void>{const db=await getDatabase();await db.run("UPDATE competition_files SET original_name=? WHERE id=?",[name,id]);},
  async setCertificate(competitionId:string,file:FileAttachment):Promise<FileAttachment|undefined>{const db=await getDatabase();const old=db.first<FileRow>("SELECT * FROM competition_files WHERE competition_id=? AND file_role='certificate' ORDER BY created_at DESC LIMIT 1",[competitionId]);await db.transaction(async()=>{await db.run("DELETE FROM competition_files WHERE competition_id=? AND file_role='certificate'",[competitionId]);await this.addFile(competitionId,file,'certificate');});return old?fileMap(old):undefined;},
};
